version: '3.8'

services:
  web:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/
