# Dockerfile.lbd
FROM public.ecr.aws/lambda/python:3.11

# 必要なパッケージをインストール
COPY requirements.txt .
RUN pip install -r requirements.txt

# アプリコードをコピー
COPY app/ app/
COPY app/handlers/lambda_handler.py .

# Lambda用ハンドラーを指定
CMD ["app.handlers.lambda_handler.handler"]
