version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - dynamodb
    networks:
      - shared-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8001:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    networks:
      - shared-network

volumes:
  dynamodb-data:

networks:
  shared-network:
    external: true
