name: Deploy to AWS Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies to build/ directory
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          mkdir -p build/python
          pip install -r requirements.txt -t build/python

      - name: Copy app and handler
        run: |
          cp -r app build/
          cp lambda_handler.py build/

      - name: Zip Lambda package
        run: |
          cd build
          zip -r ../lambda.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda.zip

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
